// Copyright 2025 Darcy Best
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "moriarty/actions.h"

#include <filesystem>
#include <fstream>
#include <iterator>
#include <memory>
#include <vector>

#include "moriarty/context.h"
#include "moriarty/internal/analysis_bootstrap.h"
#include "moriarty/internal/generation_bootstrap.h"
#include "moriarty/internal/random_engine.h"
#include "moriarty/librarian/dependencies.h"
#include "moriarty/librarian/errors.h"
#include "moriarty/problem.h"
#include "moriarty/test_case.h"

namespace moriarty {

ValidateInputBuilder::ValidateInputBuilder(Problem problem)
    : problem_(std::move(problem)) {}

ValidateInputBuilder& ValidateInputBuilder::ReadInputUsing(ReadOptions opts) {
  input_options_ = std::move(opts);
  return *this;
}

ValidateInputBuilder ValidateInput(Problem problem) {
  return ValidateInputBuilder(std::move(problem));
}

namespace {

std::string FailuresToString(
    const std::vector<DetailedValidationResult>& failures) {
  std::string result;

  for (const auto& [var_name, reason] : failures) {
    if (!result.empty()) result += "\n";
    result += reason.PrettyReason();
  }
  return result;
}

std::vector<TestCase> ReadTestCases(const ReaderFn& reader, ReadContext ctx) {
  std::vector<TestCase> test_cases = reader(ctx);
  ctx.ReadEof();

  return test_cases;
}

struct GeneratedCase {
  // The name of the generator to create this test case.
  std::string generator_name;
  // Which iteration of the calls to the generator this is from.
  int generator_call_num;
  // Which test case this is among the test cases generated by this call.
  int index;

  TestCase test_case;
};

template <typename T>
void ValidateTestCases(
    const Problem& problem, const std::vector<T>& test_cases,
    std::function<const TestCase&(const T&)> get_test_case =
        [](const T& item) -> const TestCase& { return item; }) {
  if (test_cases.empty()) {
    throw ValidationError("ValidateTestCases", "No Test Cases.");
  }

  for (int case_num = 1; const auto& item : test_cases) {
    std::vector<DetailedValidationResult> failures =
        moriarty_internal::ValidateValues(
            problem.UnsafeGetVariables(), get_test_case(item).UnsafeGetValues(),
            {}, ValidationStyle::kOnlySetVariables);
    if (!failures.empty()) {
      if (test_cases.size() == 1) {
        throw ValidationError(FailuresToString(failures));
      }
      throw ValidationError(std::format("Case #{} invalid:\n{}", case_num,
                                        FailuresToString(failures)));
    }
    case_num++;
  }
}

}  // namespace

void ValidateInputBuilder::Run() const {
  if (!input_options_) {
    throw ConfigurationError("ValidateInput::Run",
                             "std::istream needed for input. Use "
                             "ReadInputUsing() to specify options.");
  }
  // FIXME: Remove validation styles from options.
  // if (input_options_->validation != ValidationStyle::kOnlySetVariables) {
  //   throw ConfigurationError("ValidateInput::Run",
  //                            "Only ValidationStyle::kOnlySetVariables is "
  //                            "supported for input validation.");
  // }

  InputCursor cursor(input_options_->istream,
                     input_options_->whitespace_strictness);
  ReadContext ctx(problem_.UnsafeGetVariables(), cursor);

  auto reader = problem_.GetInputReader();
  if (!reader) {
    throw ConfigurationError(
        "ValidateInput::Run",
        "No InputFormat specified in Problem. Cannot read input.");
  }

  std::vector<TestCase> test_cases = ReadTestCases(*reader, ctx);
  if (test_cases.empty())
    throw ConfigurationError("ValidateInput::Run", "No Test Cases.");

  ValidateTestCases(problem_, test_cases);
}

ValidateOutputBuilder::ValidateOutputBuilder(Problem problem)
    : problem_(std::move(problem)) {}

ValidateOutputBuilder& ValidateOutputBuilder::ReadInputUsing(ReadOptions opts) {
  input_options_ = std::move(opts);
  return *this;
}

ValidateOutputBuilder& ValidateOutputBuilder::ReadOutputUsing(
    ReadOptions opts) {
  output_options_ = std::move(opts);
  return *this;
}

ValidateOutputBuilder ValidateOutput(Problem problem) {
  return ValidateOutputBuilder(std::move(problem));
}

void ValidateOutputBuilder::Run() const {
  if (!input_options_) {
    throw ConfigurationError("ValidateInput::Run",
                             "std::istream needed for input. Use "
                             "ReadInputUsing() to specify options.");
  }
  if (!output_options_) {
    throw ConfigurationError("ValidateOutput::Run",
                             "std::istream needed for output. Use "
                             "ReadOutputUsing() to specify options.");
  }
  auto input_reader = problem_.GetInputReader();
  if (!input_reader) {
    throw ConfigurationError(
        "ValidateOutput::Run",
        "No InputFormat specified in Problem. Cannot read input.");
  }
  auto output_reader = problem_.GetOutputReader();
  if (!output_reader) {
    throw ConfigurationError(
        "ValidateOutput::Run",
        "No OutputFormat specified in Problem. Cannot read output.");
  }

  InputCursor input_cursor(input_options_->istream,
                           input_options_->whitespace_strictness);
  ReadContext ctx(problem_.UnsafeGetVariables(), input_cursor);

  std::vector<TestCase> test_cases = ReadTestCases(*input_reader, ctx);
  if (test_cases.empty())
    throw ConfigurationError("ValidateOutput::Run", "No Test Cases.");
  ValidateTestCases(problem_, test_cases);

  if (test_cases.size() != 1) {
    throw ConfigurationError(
        "ValidateOutput::Run",
        "ValidateOutput currently only works with exactly 1 test case.");
  }

  InputCursor output_cursor(output_options_->istream,
                            output_options_->whitespace_strictness);
  ReadContext output_ctx(problem_.UnsafeGetVariables(),
                         test_cases[0].UnsafeGetValues(), output_cursor);
  std::vector<TestCase> output_answers =
      ReadTestCases(*output_reader, output_ctx);
  ValidateTestCases(problem_, output_answers);
}

GenerateBuilder Generate(Problem problem) {
  return GenerateBuilder(std::move(problem));
}

GenerateBuilder::GenerateBuilder(Problem problem)
    : problem_(std::move(problem)) {}

GenerateBuilder& GenerateBuilder::WriteTo(WriteOptions opts) {
  write_options_ = std::move(opts);
  return *this;
}

namespace {

std::vector<GeneratedCase> GenerateMTestCaseGenerator(
    std::string_view generator_name, int num_calls,
    std::span<int64_t> seed_with_placeholder,
    const std::unordered_map<std::string, std::string>& args,
    std::span<const std::string> input_deps,
    const moriarty_internal::VariableSet& variables,
    const std::function<std::vector<MTestCase>(GenerateContext)>& generator) {
  std::vector<GeneratedCase> test_cases;
  for (int call = 0; call < num_calls; call++) {
    seed_with_placeholder.back() = call + 1;

    moriarty_internal::ValueSet values;
    moriarty_internal::RandomEngine rng(seed_with_placeholder, "v0.1");
    GenerateContext ctx(variables, values, rng, args);

    std::vector<MTestCase> generated_cases = generator(ctx);
    for (int idx = 1; const MTestCase& test_case : generated_cases) {
      test_cases.push_back(
          {.generator_name = std::string(generator_name),
           .generator_call_num = call,
           .index = idx++,
           .test_case = TestCase(moriarty_internal::GenerateAllValues(
               variables, test_case.UnsafeGetVariables(),
               test_case.UnsafeGetValues(),
               {
                   .random_engine = rng,
                   .variables_to_generate = input_deps,
               }))});
    }
  }
  return test_cases;
}

std::vector<GeneratedCase> GenerateTestCaseGenerator(
    std::string_view generator_name, int num_calls,
    std::span<int64_t> seed_with_placeholder,
    const std::unordered_map<std::string, std::string>& args,
    const moriarty_internal::VariableSet& variables,
    const std::function<std::vector<TestCase>(GenerateContext)>& generator) {
  std::vector<GeneratedCase> test_cases;
  for (int call = 0; call < num_calls; call++) {
    seed_with_placeholder.back() = call + 1;

    moriarty_internal::ValueSet values;
    moriarty_internal::RandomEngine rng(seed_with_placeholder, "v0.1");
    GenerateContext ctx(variables, values, rng, args);

    std::vector<TestCase> generated_cases = generator(ctx);
    for (int idx = 1; TestCase& test_case : generated_cases) {
      test_cases.push_back({.generator_name = std::string(generator_name),
                            .generator_call_num = call,
                            .index = idx++,
                            .test_case = std::move(test_case)});
    }
  }
  return test_cases;
}

std::filesystem::path FormatFilename(std::string pattern,
                                     const GeneratedCase& test_case,
                                     std::string_view suffix) {
  auto replace = [&](std::string_view from, std::string_view to) {
    for (size_t pos = pattern.find(from); pos != std::string_view::npos;
         pos = pattern.find(from, pos + to.size())) {
      pattern.replace(pos, from.size(), to);
    }
  };

  replace("{gen}", test_case.generator_name);
  replace("{call}", std::to_string(test_case.generator_call_num));
  replace("{idx}", std::to_string(test_case.index));
  pattern += suffix;
  return pattern;
};

void PrintTestCase(const GenerateBuilder::WriteOptions& options,
                   const GeneratedCase& test_case,
                   const moriarty_internal::VariableSet& variables,
                   const std::optional<WriterFn>& input_writer,
                   const std::optional<WriterFn>& output_writer) {
  if (!input_writer) {
    throw ConfigurationError(
        "Generate::Run",
        "No InputFormat specified in Problem. Cannot write input.");
  }

  std::unique_ptr<std::ofstream> owned_stream;
  auto get_ostream = [&](std::string_view ext) -> std::ostream* {
    if (std::holds_alternative<GenerateBuilder::FilenamePattern>(options)) {
      const auto& pattern = std::get<GenerateBuilder::FilenamePattern>(options);
      namespace fs = std::filesystem;
      fs::path filename = FormatFilename(pattern, test_case, ext);
      fs::path parent_path = filename.parent_path();
      if (!parent_path.empty()) {
        std::error_code ec;
        fs::create_directories(parent_path, ec);
        if (ec) {
          throw ConfigurationError(
              "Generate::Run",
              std::format("Failed to create directories for '{}': {}.",
                          filename.string(), ec.message()));
        }
      }

      owned_stream = std::make_unique<std::ofstream>(filename);
      if (!owned_stream->is_open()) {
        throw ConfigurationError(
            "Generate::Run",
            std::format("Failed to open file '{}' for writing.",
                        filename.string()));
      }
      return owned_stream.get();
    } else {
      return &std::get<WriteStreams>(options).input.get();
    }
  };

  {
    std::ostream* input_os = get_ostream(".in");
    moriarty_internal::ValueSet values;
    WriteContext ctx(*input_os, variables,
                     test_case.test_case.UnsafeGetValues());
    std::invoke(*input_writer, ctx,
                std::span<const TestCase>(&test_case.test_case, 1));
  }

  if (output_writer) {
    std::ostream* output_os = get_ostream(".ans");
    moriarty_internal::ValueSet values;
    WriteContext ctx(*output_os, variables,
                     test_case.test_case.UnsafeGetValues());
    std::invoke(*output_writer, ctx,
                std::span<const TestCase>(&test_case.test_case, 1));
  }
}

}  // namespace

std::vector<TestCase> GenerateBuilder::Run() const {
  if (generators_.empty()) {
    throw ConfigurationError("Generate::Run",
                             "No generators specified. Call `Using()` to add "
                             "generators.");
  }

  std::vector<GeneratedCase> all_test_cases;
  std::span<const std::string> input_deps;
  if (problem_.GetInputDependencies()) {
    const auto& deps = *problem_.GetInputDependencies();
    input_deps = {deps.data(), deps.size()};
  }

  for (const auto& [name, generator, options] : generators_) {
    std::vector<int64_t> seed =
        problem_.BaseSeedForGenerator(options.seed.value_or(name));
    seed.push_back(0);  // Placeholder for call number

    if (std::holds_alternative<NamedGenerator::ToTestCase>(generator)) {
      const auto& gen = std::get<NamedGenerator::ToTestCase>(generator);
      std::vector<GeneratedCase> cases =
          GenerateTestCaseGenerator(name, options.num_calls, seed, options.args,
                                    problem_.UnsafeGetVariables(), gen);
      all_test_cases.insert(all_test_cases.end(),
                            std::make_move_iterator(cases.begin()),
                            std::make_move_iterator(cases.end()));
    } else {
      const auto& gen = std::get<NamedGenerator::ToMTestCase>(generator);
      std::vector<GeneratedCase> cases = GenerateMTestCaseGenerator(
          name, options.num_calls, seed, options.args, input_deps,
          problem_.UnsafeGetVariables(), gen);
      all_test_cases.insert(all_test_cases.end(),
                            std::make_move_iterator(cases.begin()),
                            std::make_move_iterator(cases.end()));
    }
  }

  // TODO: Validate after the file split occurs once we allow multiple test
  // cases per file.
  ValidateTestCases<GeneratedCase>(
      problem_, all_test_cases,
      [](const GeneratedCase& item) -> const TestCase& {
        return item.test_case;
      });

  auto include_output = [&](const GeneratedCase& test_case) {
    if (!problem_.GetOutputWriter() || !problem_.GetOutputDependencies())
      return false;

    const auto& output_deps = *problem_.GetOutputDependencies();
    // FIXME: This is technically not true, since the output may be printing a
    // static output, but that's low priority to support.
    if (output_deps.empty()) return false;
    for (const auto& var_name : output_deps) {
      if (!test_case.test_case.UnsafeGetValues().Contains(var_name)) {
        return false;
      }
    }
    return true;
  };

  if (write_options_) {
    for (const auto& test_case : all_test_cases) {
      PrintTestCase(*write_options_, test_case, problem_.UnsafeGetVariables(),
                    problem_.GetInputWriter(),
                    include_output(test_case) ? problem_.GetOutputWriter()
                                              : std::nullopt);
    }
  }

  // TODO: Consider returning the metadata as well.
  std::vector<TestCase> test_cases;
  test_cases.reserve(all_test_cases.size());
  for (auto& generated_case : all_test_cases)
    test_cases.push_back(std::move(generated_case.test_case));

  return test_cases;
}

AnalyzeBuilder::AnalyzeBuilder(Problem problem)
    : problem_(std::move(problem)) {}

AnalyzeBuilder& AnalyzeBuilder::ReadInputUsing(ReadOptions opts) {
  input_reader_ = std::move(opts);
  return *this;
}

AnalyzeBuilder& AnalyzeBuilder::ReadOutputUsing(ReadOptions opts) {
  output_reader_ = std::move(opts);
  return *this;
}

AnalyzeBuilder Analyze(Problem problem) {
  return AnalyzeBuilder(std::move(problem));
}

void AnalyzeBuilder::Run() const {
  if (!input_reader_) {
    throw ConfigurationError("Analyze::Run",
                             "std::istream needed for input. Use "
                             "ReadInputUsing() to specify options.");
  }
  if (analyzers_.empty()) {
    throw ConfigurationError("Analyze::Run",
                             "No analyzers specified. Call `Using()` to add "
                             "analyzers.");
  }

  InputCursor cursor(input_reader_->istream,
                     input_reader_->whitespace_strictness);
  ReadContext ctx(problem_.UnsafeGetVariables(), cursor);

  auto reader = problem_.GetInputReader();
  if (!reader) {
    throw ConfigurationError(
        "Analyze::Run",
        "No InputFormat specified in Problem. Cannot read input.");
  }

  std::vector<TestCase> test_cases = (*reader)(ctx);
  ctx.ReadEof();

  if (test_cases.empty())
    throw ConfigurationError("Analyze::Run", "No Test Cases read in input.");

  if (output_reader_) {
    InputCursor cursor(output_reader_->istream,
                       output_reader_->whitespace_strictness);
    ReadContext ctx(problem_.UnsafeGetVariables(), cursor);

    auto reader = problem_.GetOutputReader();
    if (!reader) {
      throw ConfigurationError(
          "Analyze::Run",
          "No OutputFormat specified in Problem. Cannot read output.");
    }

    std::vector<TestCase> outputs = (*reader)(ctx);
    ctx.ReadEof();

    if (outputs.size() != test_cases.size()) {
      throw ValidationError(
          "Analyze::Run",
          std::format("Number of output test cases ({}) does not match "
                      "number of input test cases ({}).",
                      outputs.size(), test_cases.size()));
    }

    // TODO: views::zip when we can use C++23
    for (int i = 0; i < test_cases.size(); i++) {
      test_cases[i].UnsafeGetValues().DestructiveMergeFrom(
          outputs[i].UnsafeGetValues());
    }
  }

  for (const auto& [name, analyzer] : analyzers_) {
    moriarty_internal::ValueSet values;
    AnalyzeContext ctx(problem_.UnsafeGetVariables(), values);
    analyzer(ctx, test_cases);
  }
}

}  // namespace moriarty
